// Build script to generate env.js from environment variables
// Run during Vercel build: npm run build

const fs = require('fs');
const path = require('path');

// Read environment variables
const config = {
    apiKey: process.env.FIREBASE_API_KEY || 'PLACEHOLDER',
    authDomain: process.env.FIREBASE_AUTH_DOMAIN || 'PLACEHOLDER',
    projectId: process.env.FIREBASE_PROJECT_ID || 'PLACEHOLDER',
    storageBucket: process.env.FIREBASE_STORAGE_BUCKET || 'PLACEHOLDER',
    messagingSenderId: process.env.FIREBASE_MESSAGING_SENDER_ID || 'PLACEHOLDER',
    appId: process.env.FIREBASE_APP_ID || 'PLACEHOLDER'
};

// Generate the env.js content
const envContent = `// Auto-generated by build script - DO NOT EDIT
// Generated at: ${new Date().toISOString()}

window.FIREBASE_CONFIG = ${JSON.stringify(config, null, 4)};
`;

// Write to js/env.js
const outputPath = path.join(__dirname, '..', 'js', 'env.js');

try {
    fs.writeFileSync(outputPath, envContent);
    console.log('✅ Generated js/env.js with Firebase config');
    console.log('   API Key:', config.apiKey === 'PLACEHOLDER' ? '❌ Not set' : '✅ Set');
    console.log('   Project ID:', config.projectId === 'PLACEHOLDER' ? '❌ Not set' : '✅ Set');
} catch (error) {
    console.error('❌ Failed to generate env.js:', error.message);
    process.exit(1);
}
